name: sketch_widget
description: Flutter widget to sketch widgets, transform their position, scale and rotation.
version: 1.2.2
homepage: https://github.com/fossil-engineering/sketch_widget

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
